### ISSUE TITLE
Release under libre license

### ISSUE THREAD

**Issue by throwaway1037** [Inochi2D/branding#1]
Please may this repository be released under a [libre license](https://freedomdefined.org/Licenses)?

The restrictions are arbitrary and do not respect people's freedom.

**Comment by LunaTheFoxgirl** [comment]
This repository contains no code, only branding assets, these will not be released under a libre license.

**Comment by throwaway1037** [comment]
I understand. Still, as published works, the authors have a moral duty to respect people's freedom.

**Comment by LunaTheFoxgirl** [comment]
The branding assets will not be released under a libre license, this is to make sure we can keep some sort of integrity as to what we official mark as supported/endorsed. This won't change.

**Comment by throwaway1037** [comment]
Why not say something like "only build from the official repo hosted on XYZ website are officially endorsed" or come up with something else?
As it stands, all that has been achieved is proprietary works which restrict people.

**Comment by LunaTheFoxgirl** [comment]
Only difference between barebones and full builds is that there's no branding assets (icons, logos, mascot, etc.) and the titlebar clearly states "UNSUPPORTED".
Otherwise functionality for the software is exactly the same.

**Comment by throwaway1037** [comment]
I understand. Why not just include the branding if steps have already been taken to alert the user to the fact that the build is unofficial and unsupported?

Virtually all other programs include branding even in non-supported or non-official builds and people get the message.
